### ISSUE TITLE
Add Vagrant Support to support development on local machines

### ISSUE THREAD

**Issue by nusrathbasheer91** [DevOps-Customers-J2MN/customers#1]
**As a** Developer
**I need** a way to work locally with Vagrant
**So that** members can quickly get a development environment running and can be independent of Bluemix availability

**Assumptions:**

- Use Vagrant and VirtualBox to build a local dev environment
- Python will be used for development
- Ubuntu Trusty x64 will be the OS development environment

**Acceptance Criteria:**
Given `git clone` on customers repository
And I move to the customers repository folder
And issue `vagrant up`
Then I should have a complete development environment on my workstation

**Comment by nusrathbasheer91** [comment]
Working on my local machine.

**Comment by jahnavik** [comment]
Working on my local machine as well.
