### ISSUE TITLE
Add Persistence: Change database to Redis

### ISSUE THREAD

**Issue by jahnavik** [DevOps-Customers-J2MN/customers#39]
**As a** Developer
**I need** to change the database to a persistent database 
**So that** the application survives a restart and avoids data loss, achieve resiliency

**Assumptions:**
* We will be using Redis database

**Acceptance Criteria:**
```
Given that a persistence model is added 
When the application shuts down or crashes
Then I can restart the application without losing data 
```

**Comment by nusrathbasheer91** [comment]
Closing issue. Duplicate of issue #38
