### ISSUE TITLE
Retrieve Customer using Customer ID

### ISSUE THREAD

**Issue by ARMeenakshiSundaram** [DevOps-Customers-J2MN/customers#80]
**As a** End User
**I need** to  retrieve customer details using Customer ID 
**So that** I can get all details just using Customer ID

**Assumptions:**
* Application is up and running

**Acceptance Criteria:**
```
Given a working customer application end-end
When I provide the customer ID
Then I get back all the customer details
```

**Comment by JinfanYang** [comment]
I already have finished it.
